# Example configuration for Black.

# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python.  Multiline strings are treated as
# verbose regular expressions by Black.  Use [ ] to denote a significant space
# character.

[tool.black]
line-length = 120
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | node_modules
  setup.py
)/
'''


[tool.ruff]
line-length = 120

# Enable Flake's "E" and "F" codes by default.
select = ["A", "A0", "A00", "A001", "A002", "A003", "ANN", "ANN0", "ANN00", "ANN001", "ANN002", "ANN003", "ANN1", "ANN10", "ANN101", "ANN102", "ANN2", "ANN20", "ANN201", "ANN202", "ANN204", "ANN205", "ANN206", "ANN4", "ANN40", "ANN401", "ARG", "ARG0", "ARG00", "ARG001", "ARG002", "ARG003", "ARG004", "ARG005", "B", "B0", "B00", "B002", "B003", "B004", "B005", "B006", "B007", "B008", "B009", "B01", "B010", "B011", "B012", "B013", "B014", "B015", "B016", "B017", "B018", "B019", "B02", "B020", "B021", "B022", "B023", "B024", "B025", "B026", "B027", "B9", "B90", "B904", "B905", "BLE", "BLE0", "BLE00", "BLE001", "C", "C4", "C40", "C400", "C401", "C402", "C403", "C404", "C405", "C406", "C408", "C409", "C41", "C410", "C411", "C413", "C414", "C415", "C416", "C417", "C9", "C90", "C901", "D", "D1", "D10", "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107", "D2", "D20", "D200", "D201", "D202", "D203", "D204", "D205", "D206", "D207", "D208", "D209", "D21", "D210", "D211", "D212", "D213", "D214", "D215", "D3", "D30", "D300", "D301", "D4", "D40", "D400", "D402", "D403", "D404", "D405", "D406", "D407", "D408", "D409", "D41", "D410", "D411", "D412", "D413", "D414", "D415", "D416", "D417", "D418", "D419", "E", "E4", "E40", "E402", "E5", "E50", "E501", "E7", "E71", "E711", "E712", "E713", "E714", "E72", "E721", "E722", "E73", "E731", "E74", "E741", "E742", "E743", "E9", "E90", "E902", "E99", "E999", "ERA", "ERA0", "ERA00", "ERA001", "F", "F4", "F40", "F401", "F402", "F403", "F404", "F405", "F406", "F407", "F5", "F50", "F501", "F502", "F503", "F504", "F505", "F506", "F507", "F508", "F509", "F52", "F521", "F522", "F523", "F524", "F525", "F54", "F541", "F6", "F60", "F601", "F602", "F62", "F621", "F622", "F63", "F631", "F632", "F633", "F634", "F7", "F70", "F701", "F702", "F704", "F706", "F707", "F72", "F722", "F8", "F81", "F811", "F82", "F821", "F822", "F823", "F83", "F831", "F84", "F841", "F842", "F9", "F90", "F901", "FBT", "FBT0", "FBT00", "FBT001", "FBT002", "FBT003", "I", "I0", "I00", "I001", "I2", "I25", "I252", "ICN", "ICN0", "ICN00", "ICN001", "M", "M0", "M001", "N", "N8", "N80", "N801", "N802", "N803", "N804", "N805", "N806", "N807", "N81", "N811", "N812", "N813", "N814", "N815", "N816", "N817", "N818", "PGH", "PGH0", "PGH00", "PGH001", "PLC", "PLC0", "PLC04", "PLC041", "PLC0414", "PLC2", "PLC22", "PLC220", "PLC2201", "PLC3", "PLC30", "PLC300", "PLC3002", "PLE", "PLE0", "PLE01", "PLE011", "PLE0117", "PLE0118", "PLE1", "PLE11", "PLE114", "PLE1142", "PLR", "PLR0", "PLR02", "PLR020", "PLR0206", "PLR04", "PLR040", "PLR0402", "PLR1", "PLR17", "PLR170", "PLR1701", "PLR172", "PLR1722", "PLW", "PLW0", "PLW01", "PLW012", "PLW0120", "PLW06", "PLW060", "PLW0602", "Q", "Q0", "Q00", "Q000", "Q001", "Q002", "Q003", "RET", "RET5", "RET50", "RET501", "RET502", "RET503", "RET504", "RET505", "RET506", "RET507", "RET508", "RUF", "RUF0", "RUF00", "RUF001", "RUF002", "RUF003", "RUF1", "RUF10", "RUF100", "S", "S1", "S10", "S101", "S102", "S104", "S105", "S106", "S107", "SIM", "SIM1", "SIM11", "SIM118", "T", "T1", "T10", "T100", "T2", "T20", "T201", "T203", "TID", "TID2", "TID25", "TID252", "U", "U0", "U00", "U001", "U003", "U004", "U005", "U006", "U007", "U008", "U009", "U01", "U010", "U011", "U012", "U013", "U014", "U015", "UP", "UP0", "UP00", "UP001", "UP003", "UP004", "UP005", "UP006", "UP007", "UP008", "UP009", "UP01", "UP010", "UP011", "UP012", "UP013", "UP014", "UP015", "W", "W2", "W29", "W292", "W6", "W60", "W605", "YTT", "YTT1", "YTT10", "YTT101", "YTT102", "YTT103", "YTT2", "YTT20", "YTT201", "YTT202", "YTT203", "YTT204", "YTT3", "YTT30", "YTT301", "YTT302", "YTT303"]
ignore = ["D100", "D103", "ARG001", "ANN001", "ANN201"]

# Exclude a variety of commonly ignored directories.
exclude = [".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    ".idea",
]

extend-exclude = ["tests", "setup.py"]
per-file-ignores = { }

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.10
target-version = "py39"

fix = true
